import Link from "next/link";
import { SITE } from "../../lib/site";
import { Icon } from "../../components/Icons";

export const metadata = { title: "Reliable Fiber Internet for Everyday Life" };

export default function ReliableFiberPage() {
  return <article className="article-page"><section className="article-hero alt"><div className="shell"><Link href="/blog" className="article-back"><Icon name="chevronLeft" size={18} /> Helpful notes</Link><p className="kicker light">Everyday internet</p><h1>Reliable fiber for<br />your <em>everyday life.</em></h1><p>Stable internet can make work, entertainment and staying in touch feel naturally easier.</p></div></section><section className="article-content section-space"><div className="shell article-layout"><aside><p><Icon name="router" size={18} /> Home-ready Wi-Fi</p><span>A good plan creates room for the people and devices that use it.</span></aside><div><p className="article-lead">Your connection is part of the background of your day—until it is not. Choosing a reliable fiber plan is about giving the people at home more room to work, watch, learn and share.</p><img src="/images/wifi-router.jpg" alt="Wi-Fi router" /><h2>Start with what your home needs</h2><p>Think about how many devices are online at once, whether people work or learn from home, and how often your household streams or downloads. The plan options from Amit Communications make it easy to begin that conversation.</p><p>When you are ready, use the connection form or contact the team directly. They can help you take the next step toward a stable BSNL fiber connection.</p><div className="article-callout yellow"><Icon name="bolt" size={22} /><div><strong>Want to compare speeds?</strong><span>Browse current plans from 40 Mbps through to 300 Mbps.</span><Link href="/plans" className="text-link">See all plans <Icon name="arrowRight" size={17} /></Link></div></div></div></div></section><section className="article-footer"><div className="shell"><p>Ready when you are.</p><a href={SITE.whatsappUrl} target="_blank" rel="noreferrer" className="button button-dark"><Icon name="whatsapp" size={18} /> Chat on WhatsApp</a></div></section></article>;
}
