import Link from "next/link";
import { SITE } from "../../lib/site";
import { Icon } from "../../components/Icons";

export const metadata = { title: "Stay Connected with Amit Communications" };

export default function StayConnectedPage() {
  return <article className="article-page"><section className="article-hero"><div className="shell"><Link href="/blog" className="article-back"><Icon name="chevronLeft" size={18} /> Helpful notes</Link><p className="kicker light">Connection basics</p><h1>Stay connected<br />with Amit <em>Communications.</em></h1><p>Fast, reliable BSNL fiber internet tailored for the way your home or workday stays online.</p></div></section><section className="article-content section-space"><div className="shell article-layout"><aside><p><Icon name="wifi" size={18} /> A simple idea</p><span>Good internet should support your day, not interrupt it.</span></aside><div><p className="article-lead">From streaming a favourite show to jumping on a video call, a dependable connection gives your everyday online routines a little more ease.</p><img src="/images/family-wifi.jpg" alt="Family using connected devices at home" /><h2>Connection for the moments that matter</h2><p>Amit Communications provides BSNL fiber internet designed for homes and businesses, with plan options from 40 Mbps to 300 Mbps. The right plan depends on the number of devices, the way you use the internet and the pace of your household.</p><p>Start with the essentials, compare the listed plans and talk to the team if you need help deciding. A clear connection request is only a few details away.</p><div className="article-callout"><Icon name="heart" size={22} /><div><strong>Ready to get started?</strong><span>Tell us about your connection needs and the team can guide you.</span><Link href="/get-connection" className="text-link">Get connected <Icon name="arrowRight" size={17} /></Link></div></div></div></div></section><section className="article-footer"><div className="shell"><p>Have a question instead?</p><a href={SITE.whatsappUrl} target="_blank" rel="noreferrer" className="button button-dark"><Icon name="whatsapp" size={18} /> Chat on WhatsApp</a></div></section></article>;
}
